# dev
spring:
  datasource:
    accounting:
        url: jdbc:mysql://localhost:3306/accounting
        username: app
        password: app
        driver-class-name: com.mysql.cj.jdbc.Driver
    balance:
        url: jdbc:mysql://localhost:3306/balance
        username: app
        password: app
        driver-class-name: com.mysql.cj.jdbc.Driver
    contract:
        url: jdbc:mysql://localhost:3306/contract
        username: app
        password: app
        driver-class-name: com.mysql.cj.jdbc.Driver
    finance:
        url: jdbc:mysql://localhost:3306/finance
        username: app
        password: app
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  sql:
    init.mode: always

cors-origin: http://localhost:4200

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: TRACE
        type: TRACE