# prod
spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/spmysql
    username: spmysql
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  sql:
    init.mode: always

cors-origin: https://front-sp.lm.r.appspot.com